### PR TITLE
Expand node versions to test against for Travis.

### PR DESCRIPTION
**Pull request by christophermancini**

### CODE REVIEW

**Comment by lukebakken** [comment]
Are these the officially supported versions?

**Comment by christophermancini** [comment]
@lukebakken v4 is in maintenance as LTS till 4/2018 and v6 is the new current LTS. Also, IO.js is apparently a significant fork of node. `node` and `iojs` grab the latest stable of their respective projects.

https://github.com/nodejs/LTS#lts-schedule

**Comment by lukebakken** [comment]
`iojs` merged back into `node.js` in version 4, so I don't think we need that.

**Comment by christophermancini** [comment]
Ah, ok, didn't catch that. I will remove that one. Surprised Travis still has it listed in the docs then.

**Comment by lukebakken** [comment]
:shipit: with that one change

**Pull request merged**
