### PR TITLE
Attached bucket type property operations to client object.

### PR DESCRIPTION
**Pull request by brianedgerton**
@lukebakken I don't have your test environment set up, so I tested these changes with our integration work and everything appears to be working fine. So, I'm reasonably sure I didn't break anything obvious :smile: .

### CODE REVIEW

**Comment by lukebakken** [comment]
Thanks @brianedgerton 

I opened PR #103 that adds your commit and a couple tests. I'll close this one and will get that one merged.

**Comment by brianedgerton** [comment]
@lukebakken I just got back from lunch and updated my dependency and my tests started breaking. In tracking it down it looks like the master branch and your v1.8.0 tag contain the correct source code, but the package published on `npm` is missing the code I submitted even though it has the right version number. Any idea what might have happened?

**Comment by lukebakken** [comment]
Something must have happened during the publish process. I'm looking into it now.

**Comment by lukebakken** [comment]
@brianedgerton I have published `1.8.1` to resolve this issue. Not sure what happened with the previous publish.

**Comment by brianedgerton** [comment]
Thanks! Tested and it works. Never seen that happen before when publishing to npm.

**Comment by lukebakken** [comment]
I have a script that does it (`build/publish` in the repo) and I think it barfed due to having commits to push or something like that. Not 100% sure.

**Pull request closed without merging**
